# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry_service.proto',
  package='telemetry',
  syntax='proto3',
  serialized_pb=_b('\n\x17telemetry_service.proto\x12\ttelemetry\"\x12\n\x10\x41ttitudeQRequest\"V\n\x11\x41ttitudeQResponse\x12\n\n\x02Qc\x18\x01 \x01(\x02\x12\n\n\x02Qx\x18\x02 \x01(\x02\x12\n\n\x02Qy\x18\x03 \x01(\x02\x12\n\n\x02Qz\x18\x04 \x01(\x02\x12\x11\n\ttimestamp\x18\x05 \x01(\x04\x32\xb3\x01\n\x10TelemetryService\x12K\n\x0cGetAttitudeQ\x12\x1b.telemetry.AttitudeQRequest\x1a\x1c.telemetry.AttitudeQResponse\"\x00\x12R\n\x11GetAttitudeStream\x12\x1b.telemetry.AttitudeQRequest\x1a\x1c.telemetry.AttitudeQResponse\"\x00\x30\x01\x42*\n\x14ppcbs.grpc.telemetryB\x10TelemetryServiceP\x01\x62\x06proto3')
)




_ATTITUDEQREQUEST = _descriptor.Descriptor(
  name='AttitudeQRequest',
  full_name='telemetry.AttitudeQRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=56,
)


_ATTITUDEQRESPONSE = _descriptor.Descriptor(
  name='AttitudeQResponse',
  full_name='telemetry.AttitudeQResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Qc', full_name='telemetry.AttitudeQResponse.Qc', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Qx', full_name='telemetry.AttitudeQResponse.Qx', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Qy', full_name='telemetry.AttitudeQResponse.Qy', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Qz', full_name='telemetry.AttitudeQResponse.Qz', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='telemetry.AttitudeQResponse.timestamp', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['AttitudeQRequest'] = _ATTITUDEQREQUEST
DESCRIPTOR.message_types_by_name['AttitudeQResponse'] = _ATTITUDEQRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AttitudeQRequest = _reflection.GeneratedProtocolMessageType('AttitudeQRequest', (_message.Message,), dict(
  DESCRIPTOR = _ATTITUDEQREQUEST,
  __module__ = 'telemetry_service_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.AttitudeQRequest)
  ))
_sym_db.RegisterMessage(AttitudeQRequest)

AttitudeQResponse = _reflection.GeneratedProtocolMessageType('AttitudeQResponse', (_message.Message,), dict(
  DESCRIPTOR = _ATTITUDEQRESPONSE,
  __module__ = 'telemetry_service_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.AttitudeQResponse)
  ))
_sym_db.RegisterMessage(AttitudeQResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024ppcbs.grpc.telemetryB\020TelemetryServiceP\001'))

_TELEMETRYSERVICE = _descriptor.ServiceDescriptor(
  name='TelemetryService',
  full_name='telemetry.TelemetryService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=147,
  serialized_end=326,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAttitudeQ',
    full_name='telemetry.TelemetryService.GetAttitudeQ',
    index=0,
    containing_service=None,
    input_type=_ATTITUDEQREQUEST,
    output_type=_ATTITUDEQRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAttitudeStream',
    full_name='telemetry.TelemetryService.GetAttitudeStream',
    index=1,
    containing_service=None,
    input_type=_ATTITUDEQREQUEST,
    output_type=_ATTITUDEQRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TELEMETRYSERVICE)

DESCRIPTOR.services_by_name['TelemetryService'] = _TELEMETRYSERVICE

# @@protoc_insertion_point(module_scope)
